version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: txy_pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_migrations:/pb_migrations
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    # image: txy-web:latest
    build:
      context: ./apps/web
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://tongxy.xyz:8090
    container_name: txy_web
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://tongxy.xyz:8090
      - PB_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy
